//
//  JSProjectionType.m
//  Supermap
//
//  Created by wnmng on 2018/8/9.
//  Copyright © 2018年 Facebook. All rights reserved.
//

#import "JSProjectionType.h"
#import "SuperMap/ProjectionType.h"

@implementation JSProjectionType
RCT_EXPORT_MODULE();

-(NSDictionary*)constantsToExport{
    return @{@"PRJT_NONPROJECTION":@(PRJT_NONPROJECTION),
             @"PRJT_PLATE_CARREE":@(PRJT_PLATE_CARREE),
             @"PRJT_EQUIDISTANT_CYLINDRICAL":@(PRJT_EQUIDISTANT_CYLINDRICAL),
             @"PRJT_MILLER_CYLINDRICAL":@(PRJT_MILLER_CYLINDRICAL),
             @"PRJT_MERCATOR":@(PRJT_MERCATOR),
             @"PRJT_GAUSS_KRUGER":@(PRJT_GAUSS_KRUGER),
             @"PRJT_TRANSVERSE_MERCATOR":@(PRJT_TRANSVERSE_MERCATOR),
             @"PRJT_ALBERS":@(PRJT_ALBERS),
             @"PRJT_SINUSOIDAL":@(PRJT_SINUSOIDAL),
             @"PRJT_MOLLWEIDE":@(PRJT_MOLLWEIDE),
             @"PRJT_ECKERT_VI":@(PRJT_ECKERT_VI),
             @"PRJT_ECKERT_V":@(PRJT_ECKERT_V),
             @"PRJT_ECKERT_IV":@(PRJT_ECKERT_IV),
             @"PRJT_ECKERT_III":@(PRJT_ECKERT_III),
             @"PRJT_ECKERT_II":@(PRJT_ECKERT_II),
             @"PRJT_ECKERT_I":@(PRJT_ECKERT_I),
             @"PRJT_GALL_STEREOGRAPHIC":@(PRJT_GALL_STEREOGRAPHIC),
             @"PRJT_BEHRMANN":@(PRJT_BEHRMANN),
             @"PRJT_WINKEL_I":@(PRJT_WINKEL_I),
             @"PRJT_WINKEL_II":@(PRJT_WINKEL_II),
             @"PRJT_LAMBERT_CONFORMAL_CONIC":@(PRJT_LAMBERT_CONFORMAL_CONIC),
             @"PRJT_POLYCONIC":@(PRJT_POLYCONIC),
             @"PRJT_QUARTIC_AUTHALIC":@(PRJT_QUARTIC_AUTHALIC),
             @"PRJT_LOXIMUTHAL":@(PRJT_LOXIMUTHAL),
             @"PRJT_BONNE":@(PRJT_BONNE),
             @"PRJT_HOTINE":@(PRJT_HOTINE),
             @"PRJT_STEREOGRAPHIC":@(PRJT_STEREOGRAPHIC),
             @"PRJT_EQUIDISTANT_CONIC":@(PRJT_EQUIDISTANT_CONIC),
             @"PRJT_CASSINI":@(PRJT_CASSINI),
             @"PRJT_VAN_DER_GRINTEN_I":@(PRJT_VAN_DER_GRINTEN_I),
             @"PRJT_ROBINSON":@(PRJT_ROBINSON),
             @"PRJT_TWO_POINT_EQUIDISTANT":@(PRJT_TWO_POINT_EQUIDISTANT),
             @"PRJT_EQUIDISTANT_AZIMUTHAL":@(PRJT_EQUIDISTANT_AZIMUTHAL),
             @"PRJT_LAMBERT_AZIMUTHAL_EQUAL_AREA":@(PRJT_LAMBERT_AZIMUTHAL_EQUAL_AREA),
             @"PRJT_CONFORMAL_AZIMUTHAL":@(PRJT_CONFORMAL_AZIMUTHAL),
             @"PRJT_ORTHO_GRAPHIC":@(PRJT_ORTHO_GRAPHIC),
             @"PRJT_GNOMONIC":@(PRJT_GNOMONIC),
             @"PRJT_CHINA_AZIMUTHAL":@(PRJT_CHINA_AZIMUTHAL),
             @"PRJT_NONPROJECTION_I":@(PRJT_NONPROJECTION_I),
             @"PRJT_NONPROJECTION_II":@(PRJT_NONPROJECTION_II),
             @"PRJT_SANSON":@(PRJT_SANSON),
             @"PRJT_EQUALAREA_CYLINDRICAL":@(PRJT_EQUALAREA_CYLINDRICAL),
             @"PRJT_HOTINE_AZIMUTH_NATORIGIN":@(PRJT_HOTINE_AZIMUTH_NATORIGIN),
             @"PRJT_OBLIQUE_MERCATOR":@(PRJT_OBLIQUE_MERCATOR),
             @"PRJT_HOTINE_OBLIQUE_MERCATOR":@(PRJT_HOTINE_OBLIQUE_MERCATOR),
             @"PRJT_SPHERE_MERCATOR":@(PRJT_SPHERE_MERCATOR),
             @"PRJT_BONNE_SOUTH_ORIENTATED":@(PRJT_BONNE_SOUTH_ORIENTATED),
             @"PRJT_OBLIQUE_STEREOGRAPHIC":@(PRJT_OBLIQUE_STEREOGRAPHIC)
             };
}

@end
